-- MySQL Script generated by MySQL Workbench
-- Fri Jan 11 04:04:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema book_crawler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book_crawler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_crawler` DEFAULT CHARACTER SET utf8 ;
USE `book_crawler` ;

-- -----------------------------------------------------
-- Table `book_crawler`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_crawler`.`authors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `normalize_name` VARCHAR(100) NOT NULL,
  `href` VARCHAR(200) NOT NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `normalize_name_UNIQUE` (`normalize_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_crawler`.`chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_crawler`.`chapters` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `normalize_name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `href` VARCHAR(200) NOT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_chapter_author_idx` (`author_id` ASC),
  CONSTRAINT `fk_chapter_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `book_crawler`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book_crawler`.`contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `book_crawler`.`contents` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `href` VARCHAR(200) NOT NULL,
  `data` TEXT NOT NULL,
  `chapter_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_contents_chapters1_idx` (`chapter_id` ASC),
  CONSTRAINT `fk_contents_chapters1`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `book_crawler`.`chapters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
